"""third

Revision ID: 6c7390a2334b
Revises: b7358195f46e
Create Date: 2017-12-10 17:16:42.161622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7390a2334b'
down_revision = 'b7358195f46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movies_actor_id_fkey', 'movies', type_='foreignkey')
    op.drop_column('movies', 'actor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('movies_actor_id_fkey', 'movies', 'actors', ['actor_id'], ['id'])
    # ### end Alembic commands ###
