"""six

Revision ID: 9a9f3d2dd0fc
Revises: 4b7d560f91eb
Create Date: 2017-12-10 18:47:04.904882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9f3d2dd0fc'
down_revision = '4b7d560f91eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_column('movies', 'user_id')
    # ### end Alembic commands ###
