"""first migration

Revision ID: b7358195f46e
Revises: 
Create Date: 2017-12-10 10:07:13.530190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7358195f46e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('actor_id', sa.Integer(), nullable=True))
    op.drop_constraint('movies_actors_fkey', 'movies', type_='foreignkey')
    op.create_foreign_key(None, 'movies', 'actors', ['actor_id'], ['id'])
    op.drop_column('movies', 'actors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('actors', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.create_foreign_key('movies_actors_fkey', 'movies', 'actors', ['actors'], ['id'])
    op.drop_column('movies', 'actor_id')
    # ### end Alembic commands ###
